In [11]:
#!/usr/bin/python

import time
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report, f1_score
from sklearn.neural_network import MLPClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC


def calculate_metrics(y_test, Y_predicted):
    # Calculate accuracy
    accuracy = accuracy_score(y_test, Y_predicted)
    print(f"Accuracy = {round(accuracy * 100, 2)}%")

    # Confusion Matrix
    confusion_mat = confusion_matrix(y_test, Y_predicted)
    print("\nConfusion Matrix:")
    print(confusion_mat)
    print(f"Confusion matrix shape: {confusion_mat.shape}")

    # Print TP, FP, FN, TN, Sensitivity, Specificity
    print("\nTP\tFP\tFN\tTN\tSensitivity\tSpecificity")
    for i in range(confusion_mat.shape[0]):
        TP = float(confusion_mat[i, i])  # True Positives
        FP = float(confusion_mat[:, i].sum()) - TP  # False Positives
        FN = float(confusion_mat[i, :].sum()) - TP  # False Negatives
        TN = float(confusion_mat.sum().sum()) - TP - FP - FN  # True Negatives

        sensitivity = round(TP / (TP + FN), 2) if (TP + FN) != 0 else 0.0
        specificity = round(TN / (TN + FP), 2) if (TN + FP) != 0 else 0.0

        print(f"{TP}\t{FP}\t{FN}\t{TN}\t{sensitivity}\t\t{specificity}")

    # F1 Score
    f_score = f1_score(y_test, Y_predicted, average='weighted')
    print(f"\nF1 Score (Weighted): {f_score}")


def neural_network(dataset, class_labels, test_size):
    # Load the data with the correct paths
    X = pd.read_csv(r"C:\Users\vamshinandhu\OneDrive\Desktop\project\Dataset.csv")
    Y = pd.read_csv(r"C:\Users\vamshinandhu\OneDrive\Desktop\project\Target_Labels.csv")
    
    X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=test_size, random_state=42)

    # Initialize the neural network model
    model = MLPClassifier(hidden_layer_sizes=(100), activation='logistic', random_state=42)
    model.fit(X_train, y_train)

    # Predict on the test set
    Y_predicted = model.predict(X_test)

    return y_test, Y_predicted



def random_forests(dataset, class_labels, test_size):
    # Load the data
    X = pd.read_csv(r"C:\Users\vamshinandhu\OneDrive\Desktop\project\Dataset.csv")
    Y = pd.read_csv(r"C:\Users\vamshinandhu\OneDrive\Desktop\project\Target_Labels.csv")
    X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=test_size, random_state=42)

    # Initialize the random forest classifier
    model = RandomForestClassifier(n_estimators=5, criterion='entropy', random_state=42)
    model.fit(X_train, y_train)

    # Predict on the test set
    Y_predicted = model.predict(X_test)

    return y_test, Y_predicted


def support_vector_machines(dataset, class_labels, test_size):
    # Load the data
    
    
    X = pd.read_csv(r"C:\Users\vamshinandhu\OneDrive\Desktop\project\Dataset.csv")
    Y = pd.read_csv(r"C:\Users\vamshinandhu\OneDrive\Desktop\project\Target_Labels.csv")
    X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=test_size, random_state=42)

    # Initialize the support vector machine classifier
    model = SVC(kernel='rbf', C=2.0)
    model.fit(X_train, y_train)

    # Predict on the test set
    Y_predicted = model.predict(X_test)

    return y_test, Y_predicted


def main():
    dataset = r"C:\Users\vamshinandhu\OneDrive\Desktop\project\Dataset.csv"
    class_labels = r"C:\Users\vamshinandhu\OneDrive\Desktop\project\Target_Labels.csv"
    test_size = 0.3

    # Neural Network
    print("\nRunning Neural Networks...")
    start_time = time.time()
    y_test, Y_predicted = neural_network(dataset, class_labels, test_size)
    calculate_metrics(y_test, Y_predicted)
    end_time = time.time()
    print(f"Runtime = {end_time - start_time:.2f} seconds")

    # Random Forest
    print("\nRunning Random Forests...")
    start_time = time.time()
    y_test, Y_predicted = random_forests(dataset, class_labels, test_size)
    calculate_metrics(y_test, Y_predicted)
    end_time = time.time()
    print(f"Runtime = {end_time - start_time:.2f} seconds")

    # Support Vector Machines
    print("\nRunning Support Vector Machines...")
    start_time = time.time()
    y_test, Y_predicted = support_vector_machines(dataset, class_labels, test_size)
    calculate_metrics(y_test, Y_predicted)
    end_time = time.time()
    print(f"Runtime = {end_time - start_time:.2f} seconds")


if __name__ == '__main__':
    start_time = time.time()
    main()
    end_time = time.time()
    print(f"\nTotal runtime = {end_time - start_time:.2f} seconds")



Running Neural Networks...


c:\Users\vamshinandhu\OneDrive\Desktop\project\myenv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:1119: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
c:\Users\vamshinandhu\OneDrive\Desktop\project\myenv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
c:\Users\vamshinandhu\OneDrive\Desktop\project\myenv\Lib\site-packages\sklearn\base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
c:\Users\vamshinandhu\OneDrive\Desktop\project\myenv\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A

Accuracy = 89.03%

Confusion Matrix:
[[1246  209]
 [ 155 1707]]
Confusion matrix shape: (2, 2)

TP	FP	FN	TN	Sensitivity	Specificity
1246.0	155.0	209.0	1707.0	0.86		0.92
1707.0	209.0	155.0	1246.0	0.92		0.86

F1 Score (Weighted): 0.8900091045881929
Runtime = 10.93 seconds

Running Random Forests...
Accuracy = 89.63%

Confusion Matrix:
[[1293  162]
 [ 182 1680]]
Confusion matrix shape: (2, 2)

TP	FP	FN	TN	Sensitivity	Specificity
1293.0	182.0	162.0	1680.0	0.89		0.9
1680.0	162.0	182.0	1293.0	0.9		0.89

F1 Score (Weighted): 0.8963657931056688
Runtime = 0.04 seconds

Running Support Vector Machines...
Accuracy = 90.05%

Confusion Matrix:
[[1254  201]
 [ 129 1733]]
Confusion matrix shape: (2, 2)

TP	FP	FN	TN	Sensitivity	Specificity
1254.0	129.0	201.0	1733.0	0.86		0.93
1733.0	201.0	129.0	1254.0	0.93		0.86

F1 Score (Weighted): 0.9001940197781982
Runtime = 1.03 seconds

Total runtime = 11.99 seconds
